"""delete colom userid in

Revision ID: a0d7b0c54a0b
Revises: 
Create Date: 2020-05-17 12:49:18.622249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0d7b0c54a0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='transaction')
    op.drop_constraint('transaction_ibfk_1', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('transaction_ibfk_1', 'transaction', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('user_id', 'transaction', ['user_id'], unique=True)
    # ### end Alembic commands ###
